# The Site Configuration
# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Change to your timezone
timezone: Asia/Jerusalem

# Site title
title: 0xshlomil

# Subtitle / tagline
tagline: 0xshlomil's cyber blog

# Site description (for SEO)
description: 0xshlomil's cyber blog

# Site URL
url: "https://0xshlomil.github.io"

github:
  username: 0xshlomil

twitter:
  username: 0xshlomil

social:
  name: 0xshlomil
  links:
    - https://github.com/0xshlomil
    - https://twitter.com/0xshlomil

# Google Analytics
google_analytics:
  id: G-3L25EEXQ5F

# Prefer a light theme
theme_mode: light

# Avatar image
avatar: https://avatars.githubusercontent.com/u/2356934?v=4

# Table of contents in posts
toc: true

# Pagination
paginate: 6

# Permalink structure
permalink: /:title/

# Collections
collections:
  tabs:
    output: true
    sort_by: order

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

# Default front matter
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /:title/
  - scope:
      path: _tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

# Build exclusions
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "gulpfile.js"
  - "node_modules"
  - "package*.json"

plugins:
  - jekyll-seo-tag

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
